<a href="https://colab.research.google.com/github/harshnsolanki/Machine_Learning_Part_1/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import random

Creating a numpy array with random values

In [4]:
np.random.randint(1,10,size=(5,5))

array([[1, 5, 2, 6, 4],
       [8, 2, 4, 8, 5],
       [8, 1, 1, 6, 1],
       [2, 9, 8, 3, 6],
       [1, 4, 8, 1, 3]])

Array of evenly spaced values --> Specifying numbers that we want

In [11]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

Array of evenly spaced values -> Specifying steps

In [12]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [14]:
# Converting a list into numpy array

lst = [1,2,3,4,5,6,7,8,9]
print(type(lst), " Values:", lst)

n_lst = np.array(lst)
print(type(n_lst), " Values:", n_lst)

<class 'list'>  Values: [1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'numpy.ndarray'>  Values: [1 2 3 4 5 6 7 8 9]


Analysing Numpy Array

In [16]:
n_array = np.random.randint(1,20,size=(5,5))
n_array

array([[ 2,  5,  9, 18, 12],
       [12,  5, 13,  9, 11],
       [18,  4, 18, 12, 14],
       [16,  2, 17,  2,  8],
       [ 4, 16,  2, 18, 18]])

In [19]:
# array dimension
print(np.ndim(n_array)) # For dimension
print(np.shape( n_array))

2
(5, 5)


In [20]:
# Number of elements in the array
np.size(n_array)

25

In [25]:
# Checking the datatype values in the array
print(n_array.dtype)

int64


Mathemetical Operations on NumpyArray

In [26]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # it will concate two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [27]:
np.array(list1) + np.array(list2)

array([ 7,  9, 11, 13, 15])

In [28]:
a = np.random.randint(0,10,size=(3,3))
b = np.random.randint(10,20,size=(3,3))
print(a)
print(b)

[[2 8 3]
 [8 3 0]
 [5 5 8]]
[[19 16 12]
 [19 12 13]
 [15 15 19]]


In [29]:
np.array(a+b)    # Element wise addition

array([[21, 24, 15],
       [27, 15, 13],
       [20, 20, 27]])

In [30]:
print(a-b)
print(a*b)
print(a/b)

[[-17  -8  -9]
 [-11  -9 -13]
 [-10 -10 -11]]
[[ 38 128  36]
 [152  36   0]
 [ 75  75 152]]
[[0.10526316 0.5        0.25      ]
 [0.42105263 0.25       0.        ]
 [0.33333333 0.33333333 0.42105263]]


In [35]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[21 24 15]
 [27 15 13]
 [20 20 27]]
[[-17  -8  -9]
 [-11  -9 -13]
 [-10 -10 -11]]
[[ 38 128  36]
 [152  36   0]
 [ 75  75 152]]
[[0.10526316 0.5        0.25      ]
 [0.42105263 0.25       0.        ]
 [0.33333333 0.33333333 0.42105263]]
