<a href="https://colab.research.google.com/github/harshnsolanki/Machine_Learning_Part_1/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import random

Creating a numpy array with random values

In [2]:
np.random.randint(1,10,size=(5,5))

array([[2, 8, 6, 3, 8],
       [9, 6, 9, 5, 3],
       [8, 3, 5, 7, 2],
       [6, 3, 7, 7, 5],
       [6, 5, 3, 9, 6]])

Array of evenly spaced values --> Specifying numbers that we want

In [3]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

Array of evenly spaced values -> Specifying steps

In [4]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [5]:
# Converting a list into numpy array

lst = [1,2,3,4,5,6,7,8,9]
print(type(lst), " Values:", lst)

n_lst = np.array(lst)
print(type(n_lst), " Values:", n_lst)

<class 'list'>  Values: [1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'numpy.ndarray'>  Values: [1 2 3 4 5 6 7 8 9]


Analysing Numpy Array

In [6]:
n_array = np.random.randint(1,20,size=(5,5))
n_array

array([[17, 15, 10,  2, 11],
       [13,  5, 14,  1,  4],
       [ 2, 16, 17,  7,  9],
       [14, 16,  3,  6, 17],
       [ 4,  6,  2, 11, 11]])

In [7]:
# array dimension
print(np.ndim(n_array)) # For dimension
print(np.shape( n_array))

2
(5, 5)


In [8]:
# Number of elements in the array
np.size(n_array)

25

In [9]:
# Checking the datatype values in the array
print(n_array.dtype)

int64


Mathemetical Operations on NumpyArray

In [10]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # it will concate two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [11]:
np.array(list1) + np.array(list2)

array([ 7,  9, 11, 13, 15])

In [12]:
a = np.random.randint(0,10,size=(3,3))
b = np.random.randint(10,20,size=(3,3))
print(a)
print(b)

[[0 3 2]
 [6 1 7]
 [8 8 3]]
[[15 19 17]
 [15 10 14]
 [19 19 11]]


In [13]:
np.array(a+b)    # Element wise addition

array([[15, 22, 19],
       [21, 11, 21],
       [27, 27, 14]])

In [14]:
print(a-b)
print(a*b)
print(a/b)

[[-15 -16 -15]
 [ -9  -9  -7]
 [-11 -11  -8]]
[[  0  57  34]
 [ 90  10  98]
 [152 152  33]]
[[0.         0.15789474 0.11764706]
 [0.4        0.1        0.5       ]
 [0.42105263 0.42105263 0.27272727]]


In [15]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[15 22 19]
 [21 11 21]
 [27 27 14]]
[[-15 -16 -15]
 [ -9  -9  -7]
 [-11 -11  -8]]
[[  0  57  34]
 [ 90  10  98]
 [152 152  33]]
[[0.         0.15789474 0.11764706]
 [0.4        0.1        0.5       ]
 [0.42105263 0.42105263 0.27272727]]


Array Manuplation

In [16]:
array_1 = np.random.randint(0,10,(2,3))
print(array_1)
print(array_1.shape)

[[7 0 3]
 [9 9 9]]
(2, 3)


In [20]:
# Tarnspose of an array
trans_array_1 = np.transpose(array_1)
print(trans_array_1)
print(trans_array_1.shape)
print(trans_array_1.dtype)

[[7 9]
 [0 9]
 [3 9]]
(3, 2)
int64


In [22]:
# reshaping the arrray
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[2 8 3]
 [1 4 9]]
(2, 3)


In [24]:
b = a.reshape((3,2))
print(b)

[[2 8]
 [3 1]
 [4 9]]
